### ISSUE TITLE
there is a error in phpstorm

### ISSUE THREAD

**Issue by Chasers9527** [ChrisCarini/environment-variable-settings-summary-intellij-plugin#2]
error with setting. 

PHPstorm infomation:

PhpStorm 2019.1.3
Build #PS-191.7479.51, built on June 18, 2019
Licensed to jetbrains js
Subscription is active until November 27, 2019
JRE: 1.8.0_202-release-1483-b53 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6

can you fix this bug

```java
java.lang.ExceptionInInitializerError
	at com.chriscarini.jetbrains.settingssummary.environmentvariables.settings.SettingsConfigurable.getDisplayName(SettingsConfigurable.java:35)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getDisplayName(ConfigurableWrapper.java:131)
	at com.intellij.openapi.options.newEditor.SettingsTreeView$MyNode.<init>(SettingsTreeView.java:496)
	at com.intellij.openapi.options.newEditor.SettingsTreeView$MyNode.<init>(SettingsTreeView.java:484)
	at com.intellij.openapi.options.newEditor.SettingsTreeView$MyRoot.buildChildren(SettingsTreeView.java:477)
	at com.intellij.ui.treeStructure.CachingSimpleNode.getChildren(CachingSimpleNode.java:39)
	at com.intellij.ui.treeStructure.SimpleTreeStructure.getChildElements(SimpleTreeStructure.java:27)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.addToCache(FilteringTreeStructure.java:66)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.rebuild(FilteringTreeStructure.java:61)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.<init>(FilteringTreeStructure.java:53)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.<init>(FilteringTreeStructure.java:44)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeBuilder.<init>(FilteringTreeBuilder.java:53)
	at com.intellij.openapi.options.newEditor.SettingsTreeView$MyBuilder.<init>(SettingsTreeView.java:898)
	at com.intellij.openapi.options.newEditor.SettingsTreeView.<init>(SettingsTreeView.java:183)
	at com.intellij.openapi.options.newEditor.SettingsDialog.treeViewFactory(SettingsDialog.java:68)
	at com.intellij.openapi.options.newEditor.SettingsEditor.<init>(SettingsEditor.java:158)
	at com.intellij.openapi.options.newEditor.SettingsDialog.<init>(SettingsDialog.java:62)
	at com.intellij.openapi.options.newEditor.SettingsDialogFactory.create(SettingsDialogFactory.java:41)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getDialog(ShowSettingsUtilImpl.java:44)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:84)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:54)
	at com.intellij.ide.MacOSApplicationProvider$Worker.lambda$null$1(MacOSApplicationProvider.java:104)
	at com.intellij.ide.MacOSApplicationProvider$Worker.lambda$submit$7(MacOSApplicationProvider.java:177)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:74)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.util.MissingResourceException: Can't find bundle for base name messages.envVarMain, locale zh_CN
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:782)
	at com.chriscarini.jetbrains.messages.Messages.<clinit>(Messages.java:14)
	... 45 more
```

**Comment by ChrisCarini** [comment]
Hey @Chasers9527,

Thank you for raising this issue! There was no default resource bundle (nor one for `zh`) which was causing this issue. I've fixed this by creating a default resource bundle.

In the mean time, I've published a new version which is waiting JetBrains approval - you should expect to see `0.0.5` [on the JetBrains Plugin page](https://plugins.jetbrains.com/plugin/10998-environment-variable-settings-summary/versions) in a day or so.

Given your locale is set to `zh`, do you feel comfortable helping me translate a few lines so I can make a language-specific bundle for `zh`? If so, I'll create a new issue and we can track the addition of `zh` there. :)

Best,
@ChrisCarini

**Comment by Chasers9527** [comment]
@ChrisCarini what can I do for you,  translate a envVarMain_zh.properties ?  I think i can do it ~

**Comment by Chasers9527** [comment]
@ChrisCarini 

```bash
environment.variables=环境变量
environment.variables.settings=环境变量设置
exclude.variable.names=排除变量名称
exclude.variable.names.tooltip=多种环境变量可以通过逗号分隔开
exclude.variable.table.tooltip=当前环境变量 - 红色的已标记为排除选项
```

**Comment by ChrisCarini** [comment]
@Chasers9527 - yes that would be great! I just created #3 to track this! :)

**Comment by ChrisCarini** [comment]
@all-contributors please add @youmikuang for bug
